project:
  type: website

website:
  title: "Statistics  for Engineering"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - intro_stat.qmd
      - continuous_r.v.qmd
      - some_special_continuous r.v.qmd
      #- references.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

bibliography: references.bib

execute: 
  echo: false
  warning: false